language: node_js
node_js:
  - "12"
  - "14"
script: 
  - yarn run lint
  - yarn run test
before_deploy:
  - yarn build:esm && yarn build:cjs
jobs:
  include:
    - stage: release
      node_js: "14"
      deploy:
        provider: "script"
        skip_cleanup: true
        script:
          - yarn semantic-release
